### ISSUE TITLE
Game breaks when i look into a certain block, in this case a player head triggers the bug

### ISSUE THREAD

**Issue by cucojr** [Aureljz/SimplyHouses-Forge#1]
https://user-images.githubusercontent.com/112745988/188258171-4839cf01-5785-40f7-97ef-7142a1288465.mp4

it doesnt apply only with that block, there are other blocks that do the same.
an example are those books next to the cake, it does the same if i look directly, it crashes
![image](https://user-images.githubusercontent.com/112745988/188258360-8a0ab90d-c140-4444-b0f5-14db71c468e6.png)
And here is a piece of log
[latest.txt](https://github.com/Aureljz/SimplyHouses-Forge/files/9481915/latest.txt)
nvm i somehow fixed it

**Comment by leobaccili** [comment]
How you solve it?
